FROM python:3.9-slim

WORKDIR /app
COPY . .

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git golang wkhtmltopdf && \
    rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt && \
    chmod +x setup.sh && \
    ./setup.sh

VOLUME ["/app/scans"]
ENTRYPOINT ["python", "scripts/websentry.py"]
